# 2b2t restart plugin

# Set to 99999999 to restart exactly at your specified time
# If the players are not low for 5 days then the server will forcefully restart even if there is a ton of players online.
MinimumPlayersToRestart: 4

# Time to where the server will call a restart,
# if the server hasn't reached the minimum number of players to restart it will wait until the player count has been reached,
# then it will start a 15 minute countdown.
# List of timezones: https://garygregory.wordpress.com/2013/06/18/what-are-the-java-timezone-ids/
Timezone: "America/New_York"
# Time
# 2:00 AM EST
Hour: 2
Minute: 0
Seconds: 0
